//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bagisla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoktorDetay
    {
        public System.Guid ID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string UzmanlikDali { get; set; }
        public string Unvan { get; set; }
        public string Tel { get; set; }
        public string Adres { get; set; }
        public string Il { get; set; }
        public string Ilce { get; set; }
        public string Fotograf { get; set; }
        public string T_C { get; set; }
    
        public virtual aspnet_Membership aspnet_Membership { get; set; }
        public virtual aspnet_Membership aspnet_Membership1 { get; set; }
    }
}
