//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bagisla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Iletisim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Iletisim()
        {
            this.Mesajlars = new HashSet<Mesajlar>();
        }
    
        public int INo { get; set; }
        public string Email { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<int> Hasta_No { get; set; }
        public Nullable<int> Bagis_No { get; set; }
        public string TelNo { get; set; }
        public Nullable<int> MesajNo { get; set; }
    
        public virtual BagisVeren BagisVeren { get; set; }
        public virtual Hastalar Hastalar { get; set; }
        public virtual Mesajlar Mesajlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mesajlar> Mesajlars { get; set; }
    }
}
