//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bagisla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesajlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mesajlar()
        {
            this.Iletisims = new HashSet<Iletisim>();
        }
    
        public int MesajNo { get; set; }
        public string Mesaj { get; set; }
        public Nullable<int> Hasta_No { get; set; }
        public Nullable<int> Bagis_No { get; set; }
        public Nullable<int> INo { get; set; }
        public string Ad { get; set; }
        public string Email { get; set; }
        public string Konu { get; set; }
    
        public virtual BagisVeren BagisVeren { get; set; }
        public virtual Hastalar Hastalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Iletisim> Iletisims { get; set; }
        public virtual Iletisim Iletisim { get; set; }
    }
}
