//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bagisliyorum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BagisVeren
    {
        public int Bagis_No { get; set; }
        public string Kull_Adi { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Sifre { get; set; }
        public System.DateTime Dogum_Tarihi { get; set; }
        public string Fotograf { get; set; }
        public string Video { get; set; }
        public string TC_No { get; set; }
        public Nullable<decimal> Miktar { get; set; }
        public int Kull_No { get; set; }
        public int Hasta_No { get; set; }
    }
}
