//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bagisliyorum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hastaliklar
    {
        public int HNo { get; set; }
        public string HastalikAdi { get; set; }
        public string Aciklama { get; set; }
        public int Hasta_No { get; set; }
        public int Kull_No { get; set; }
        public int Bagis_No { get; set; }
        public int INo { get; set; }
    }
}
