//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bagisliyorum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanicilar
    {
        public int Kull_No { get; set; }
        public string Kull_Adi { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Sifre { get; set; }
        public string Kull_Turu { get; set; }
        public int Hasta_No { get; set; }
        public int Bagis_No { get; set; }
    }
}
